"""baseline schema

Creates the full v1 schema from the SQLAlchemy metadata. Subsequent migrations
should be autogenerated (`alembic revision --autogenerate -m "..."`).

Revision ID: 0001
Revises:
Create Date: 2026-06-19
"""
from alembic import op

from app.core.database import Base
from app import models  # noqa: F401  (populate metadata)

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
